name: 'General Push'
description: 'Developing...'
body:
  - type: textarea
    id: feature-list
    attributes:
      label: 'Feature'
      description: '*List* key features below'
      placeholder: 'no?'
    validations:
      required: true
  - type: textarea
    id: mentions
    attributes:
      label: 'Mentions'
      description: '@someone maybe'
      placeholder: ''
  - type: textarea
    id: description
    attributes:
      label: 'Description'
      description: 'Type anything as long as you want.'
      placeholder: 'Explain something in detail.'
    validations:
      required: true
